export {default as SplashSceen} from "./Splash"
export {default as Onboarding} from "./Onboarding"
export {default as Home} from "./Home"
export {default as Tracking} from "./Tracking"
export {default as Vendors} from "./Vendors"
export {default as Riders} from "./Riders"