export {default as Home} from "./Home"
export {default as Vendors} from "./Vendors"
export {default as Riders} from "./Riders"
export {default as PrivacyPolicy} from "./PrivacyPolicy"
export {default as Contact} from "./Contact"
export {default as TermsAndConditions} from "./TermsAndConditions"